name: CI

on:
  push: ~
  pull_request: ~

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: |
            packages/*/package-lock.json
            package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Build & lint & test
        run: npm run all
