name: Publish

on:
  push:
    tags: ['**']

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: npm install
    - name: Build & lint & test
      run: npm run all
    - name: Set NPM Env for publish
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
    - name: Login to VS Code extension hub
      run: 'npx vsce login hugo-vrijswijk -p ${{ secrets.VSCODE_TOKEN }}'
    - name: Publish
      run: npx lerna publish from-git --yes
