name: Publish

on:
  push:
    tags: ['**']

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
        with:
          # Fetch all commits, used by lerna
          fetch-depth: 0
      # Fetch all tags
      - run: git fetch --all
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build & lint & test
        run: npm run all
      - name: Set NPM Env for publish
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Publish
        run: npx lerna publish from-git --yes
        env:
          VSCODE_TOKEN: ${{ secrets.VSCODE_TOKEN }}
          OVSX_TOKEN: ${{ secrets.OVSX_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
